# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\"[\n\x0cWeatherAlert\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x12\n\nwind_speed\x18\x04 \x01(\x02\"<\n\x18WeatherAlertConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Y\n\x17UserNotificationService\x12>\n\x10SendWeatherAlert\x12\r.WeatherAlert\x1a\x19.WeatherAlertConfirmation\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERALERT']._serialized_start=22
  _globals['_WEATHERALERT']._serialized_end=113
  _globals['_WEATHERALERTCONFIRMATION']._serialized_start=115
  _globals['_WEATHERALERTCONFIRMATION']._serialized_end=175
  _globals['_USERNOTIFICATIONSERVICE']._serialized_start=177
  _globals['_USERNOTIFICATIONSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
